language: java

sudo: required

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
  - ssh -f -o StrictHostKeyChecking=no -i /home/travis/.ssh/id_rsa root@45.76.87.200 "./pik-deploy"

after_failure:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
